name: Check Banned Tables

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'release/*'
      - 'feature/*'

jobs:
  check-banned-tables:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run banned tables check
      run: python sql_github_action_test/check_banned_tables.py config/banned_tables.txt
